### ISSUE TITLE
Fix failing Travis linter checks

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#100]
run flake8 shopyo before PR to fix all pep8 errors.

**Comment by anir1ghosh** [comment]
Hey! I can take this up if no one else is working already. I plan to fix the pep8 errors by creating 1 PR for each module and fix them separately to avoid any conflicts and a big PR. Let me know if that sounds alright?

**Comment by Abdur-rahmaanJ** [comment]
@anir1ghosh Great idea! Assigned you. There are too many errors, one PR is nice!

**Comment by Abdur-rahmaanJ** [comment]
See the current list here: https://travis-ci.com/github/Abdur-rahmaanJ/shopyo/builds/153936886 :mag:
