### ISSUE TITLE
Add tox for tests

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#107]

**Comment by jugmac00** [comment]
Thanks for re-opening the issue!

Was a bit too short notice for me to do the lightning talk - but I will add support for `tox` anyway - if you still like it.

**Comment by Abdur-rahmaanJ** [comment]
Aie you scrambled a real nice plan B, i was reviewing issues and i thought of closing the most improbable ones

**Comment by Abdur-rahmaanJ** [comment]
Most welcomed to add tox 💯 We were pretty lax on tests but it caused missed spotlight opportunities such as this one. We'll have to take this seriously ~
