### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name' when trying to Edit the Category name

### ISSUE THREAD

**Issue by memoglr** [Abdur-rahmaanJ/shopyo#138]
When I try to 'Edit' the Category name it gives an 'AttributeError'

![AttributeError](https://user-images.githubusercontent.com/48573164/92537250-484b3980-f201-11ea-813e-fd8b3dfbb3a3.png)

**Comment by Abdur-rahmaanJ** [comment]
Thanks for the issue. You ran it online or locally?

**Comment by memoglr** [comment]
Hello, I ran it locally. 

Saludos Cordiales!
Guillermo López
On Sep 13, 2020 05:05, Abdur-Rahmaan Janhangeer <notifications@github.com> wrote:
Thanks for the issue. You ran it online or locally?

**Comment by memoglr** [comment]
Abdur, I would like to contribute on the project but not sure and how or where to begin, could you give me a han on this? 

Thanks. 
Guillermo López
On Sep 13, 2020 05:05, Abdur-Rahmaan Janhangeer <notifications@github.com> wrote:
Thanks for the issue. You ran it online or locally?

**Comment by Abdur-rahmaanJ** [comment]
Great, read this: https://dev.to/abdurrahmaanj/shopyo-enhance-your-flask-by-exploring-an-advanced-flask-app-40j3 and then mail me at arj.python@gmail.com I'll be glad to help!

**Comment by memoglr** [comment]
Fixed on commit 8210325
