### ISSUE TITLE
Flask: Add people section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#14]
add another view -> people, see products or appointments and do the same | any help needed ask!

People need the following:
- Name
- Surname
- Age
- Info

Others as needed

You are expected to add an icon in nav.

**Comment by ParinitaChowdhry** [comment]
i want to contribute. is it okay if i can do this by 27th July?

**Comment by Lutrome** [comment]
I'd like to contribute as well.

**Comment by Abdur-rahmaanJ** [comment]
@ParinitaChowdhry ok np, for the people section, just we did some update and ... just see how the other sections were implemented, we are really sorry for not providing proper docs.

@Lutrome are you willing to start making the point of sales section? Which will sell products specified in the model?

**Comment by Lutrome** [comment]
Yes, I’ll start the point of sales section.

**Comment by Abdur-rahmaanJ** [comment]
@Lutrome can you see issue #24 and comment there, so that github will allow me assigning this issue to you!

**Comment by ParinitaChowdhry** [comment]
@Abdur-rahmaanJ : i think we do not need to store age in people model as it is calculated field, shall I remove it?

**Comment by blips5** [comment]
Hi @ParinitaChowdhry  
Can i ask a couple questions.
Should age be removed or swapped for another value i.e.
Do you think it should be a date? so age can be calculated. keeping peoples age correct and up to date.
or
have you got any other ideas of storing age?

**Comment by Abdur-rahmaanJ** [comment]
@ParinitaChowdhry or it can be added in models just for records i.e. calculated before inserting in db. might be useful to skip client side work. but definitely not needed to ask user to input age.

**Comment by ParinitaChowdhry** [comment]
Hi @Abdur-rahmaanJ : 
I see there is a people model. We store : name, age, birthday, about and social_media.
I propose not storing age as birthday is being stored. we may calculate age if required.
I will be adding validation for unique name. Do u have a min age to be validated? any suggestions for social media input validation?
Thanks.

**Comment by Abdur-rahmaanJ** [comment]
@ParinitaChowdhry no worry for social media validation. Calculating age might be a pain, better store it. Yes, unique name is a must but i think unique id better as name can be same.

**Comment by Abdur-rahmaanJ** [comment]
@ParinitaChowdhry just updated project for cleaner templates, just folderised everything, please have a look

**Comment by ParinitaChowdhry** [comment]
@Abdur-rahmaanJ : i committed my changes n merged them. I am not sure why I do not see them when i access the project via github. Please help to see if everything ok.

**Comment by blips5** [comment]
@ParinitaChowdhry  did u issue a PR.

**Comment by blips5** [comment]
@ParinitaChowdhry  Just see your PR.  it has been closed, did you delete your branch before the pull request had been merged. :smiley_cat:

**Comment by ParinitaChowdhry** [comment]
@blips5: i re-opened the PR.

**Comment by Abdur-rahmaanJ** [comment]
![shopyo_people](https://user-images.githubusercontent.com/22630684/62426668-d567b900-b6f8-11e9-91d3-1edd4e5069ef.png)

@ParinitaChowdhry Check age, bit weird ^^_

Also, can you add name, mail and address section and instead of social media add facebook, twitter and linkedin?

**Comment by ParinitaChowdhry** [comment]
@Abdur-rahmaanJ : to clarify, you want to add separate sections each for name, mail and address and facebook, twitter and linkedin? or change details in people section and instead of social media, display facebook, twitter and linkedin?

**Comment by Abdur-rahmaanJ** [comment]
@ParinitaChowdhry modify people replace social media by fb linkedin etc
