### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by flide** [Abdur-rahmaanJ/shopyo#140]
When I try to run the project, I encounter a error during the "initialise" phase. Is this the right place to ask for help for such silly stuff?

**Comment by memoglr** [comment]
Hello @flide  try to delete the shopyo.db from the shopyo/shopyo folder, do a 'python manage.py clean' and than 'python manage.py initialise'

**Comment by flide** [comment]
cool! That fixed it for me. It might be nice to update this info in the README. 
Doofuses like me won't irk you no more.

**Comment by Abdur-rahmaanJ** [comment]
@flide thanks for report !
