### ISSUE TITLE
Repeated base.html

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#15]
Hi,
 Been checking  out the Shopyo app and noticed the base.html is repeated for each section of pages.
would it not be cleaner to have only one standard base template.

**Comment by Abdur-rahmaanJ** [comment]
@blips5 try implementing it without breaking anything, i think yes it will be cleaner

**Comment by blips5** [comment]
@Abdur-rahmaanJ
  I've had a little play around and made some changes and also separated the navigation menu.  will Just need to make sure i haven't broke anything like you said.  :)

**Comment by Abdur-rahmaanJ** [comment]
@blips5 the base was repeated because each nav needed to be different
