### ISSUE TITLE
add/edit products input for vat_price and sell_price does not take float values.

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#17]
I've noticed that the input values for vat_price and sell price on the product_add / product_edit will only accept int values would this not be better to change from:

` <input type="number">`

to 

`<input type="text">`

![products_add](https://user-images.githubusercontent.com/33946380/61300860-ac7b9480-a7da-11e9-8484-fc799f7cc787.gif)

**Comment by Zernerus** [comment]
@blips5 You could also use 
`<input type="number" step="0.01">`
But I agree with you that it should accept decimals

**Comment by Abdur-rahmaanJ** [comment]
@blips5 yes it should! You added it in your PR?

**Comment by blips5** [comment]
@Zernerus  Thanks for the comment learn something new everyday. 

@Abdur-rahmaanJ  No i  have not :(
