### ISSUE TITLE
Help info for contributing.

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#18]
How do we go about setting up information helping new contributors.

Does this need a new file. such as contributing.md ?

**Comment by Abdur-rahmaanJ** [comment]
no include it in readme for now

**Comment by blips5** [comment]
ok no problem i will get on this later. I have written a howto for add new sections to templates.

**Comment by arthurarty** [comment]
@Abdur-rahmannJ @blips5 I think this issue can be closed.
