### ISSUE TITLE
appointment_add allows historic dates.

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#19]
![add_appointment](https://user-images.githubusercontent.com/33946380/61370692-f2903100-a88a-11e9-8490-30f3e5250b05.gif)

**Comment by Abdur-rahmaanJ** [comment]
You mean we tell people to contribute this feature?

**Comment by blips5** [comment]
ye i think maybe historic dates for adding appointments should not be allowed
but not to sure.

**Comment by Abdur-rahmaanJ** [comment]
woops yes! noticed it!

**Comment by rajansaini691** [comment]
Hello, this is my first open-source contribution! I just wrote a little bit of javascript in the appointment_add template to do some client-side checking on a local repo, do you want to check it out?

**Comment by blips5** [comment]
@rajansaini691 Are you still interested in tackling this.
 first timers are welcome. 😄 

you can add your country in readme.md when your PR has been accepted.

**Comment by iryanjan18** [comment]
Is this still an issue? Let me know so I could try to work it out

**Comment by blips5** [comment]
@iryanjan18  yes this is still an isusse.

**Comment by hazeliao** [comment]
Hi, I tried working this issue out and I think I got it fixed. This is my first PR to a github project, I'm doing hacktoberfest 2019 😅
