### ISSUE TITLE
Delete button for appointments opens new tab.

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#21]
On clicking the confirm delete button it opens a new tab.

![del_appointment](https://user-images.githubusercontent.com/33946380/61414784-bab6d700-a8e6-11e9-8452-09257976d6c8.gif)

**Comment by Abdur-rahmaanJ** [comment]
should be easy to fix. just prevent it. modify js.

**Comment by blips5** [comment]
Would you like me to take on this issue?

**Comment by Abdur-rahmaanJ** [comment]
ok!

**Comment by Abdur-rahmaanJ** [comment]
@blips5 added you as collab, check mail to accept

**Comment by Abdur-rahmaanJ** [comment]
i got this issue yesterday
