### ISSUE TITLE
Some of the HTML page title tags need correcting. 

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#22]
some of the title tags are wrong and need correcting to meaningful names.  nice easy task for someone. 😄

**Comment by Abdur-rahmaanJ** [comment]
@blips5 give more example

**Comment by blips5** [comment]
On the manufacturer index page the HTML title tag is set as SpareParts

![bad_T_tag](https://user-images.githubusercontent.com/33946380/61453679-b3c7ad00-a956-11e9-8d10-25e997340b61.GIF)

This is the code in manufac_index.html

![code_tag](https://user-images.githubusercontent.com/33946380/61453708-cd68f480-a956-11e9-9e8c-4a149ec8dcf6.GIF)

**Comment by CommandReverse** [comment]
Change something into meaningful names. This is something I could do. I have been looking into the issues and was kinda scared to start. So let's start here and see if I can be of service.

**Comment by Abdur-rahmaanJ** [comment]
@CommandReverse basically we have been focusing on Python. Html checks should be nice! If you need help setting up the project, please tell!

**Comment by CommandReverse** [comment]
@Abdur-rahmaanJ I got the repository pulled and will be able to start in a different branch. Manually HTML check or is it something we can do via script? I don't know exactly the expectation

**Comment by CommandReverse** [comment]
Started checking and changing content of the tags for the fitting equivalent. Due to being homebound for some weeks, I don't have any commute and will be able to help more.
