### ISSUE TITLE
404 error for styles.css and logic.js

### ISSUE THREAD

**Issue by blips5** [Abdur-rahmaanJ/shopyo#30]
Should these files be created or just comment out the requests for now?

Just find them annoying that's all 😃

**Comment by Abdur-rahmaanJ** [comment]
yes yes

**Comment by CommandReverse** [comment]
@blips5 If you could elaborate a bit, I could take this one on.

**Comment by Abdur-rahmaanJ** [comment]
There was a 404 error on style.css and script.js not found on loading pages. If it's still there, remove those two lines in base module template

**Comment by CommandReverse** [comment]
I'll have a look into it today. If you want, you can assign it to me

**Comment by Abdur-rahmaanJ** [comment]
Done
