### ISSUE TITLE
How to separate sections as modules?

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#33]

**Comment by Abdur-rahmaanJ** [comment]
@blips5

**Comment by Abdur-rahmaanJ** [comment]
We might organise templates as such 

- https://www.digitalocean.com/community/tutorials/how-to-structure-large-flask-applications

instead of prods_ ..., prods_ ...

**Comment by blips5** [comment]
@Abdur-rahmaanJ  I've had a quick look at the link 😄 . I'll do some investigating for this.

**Comment by Abdur-rahmaanJ** [comment]
done templates separation

**Comment by blips5** [comment]
@Abdur-rahmaanJ  I've made a start on the models and views. 😸

**Comment by Abdur-rahmaanJ** [comment]
@blips5 

```
admin=Blueprint('admin',__name__,template_folder='templates')
```

templates key

**Comment by Abdur-rahmaanJ** [comment]
Done!!! :tada:
