### ISSUE TITLE
Flask: Complete people section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#44]
Add 

- Mail
- Phone number
- Facebook instead of Social Media
- Twitter 
- Linkedin

**Comment by mghall25** [comment]
Hi. I have some experience with Flask and think I can take this on.  Could you please provide a little more information about this task? The /people/add page looks like it's adding the record correctly to the database.

**Comment by blips5** [comment]
@mghall25 
Hi, yes the data fields have been completed. Could possibly add a peoples look up like the appointments and product pages.

😸

**Comment by mghall25** [comment]
@blips5 My code for people search is ready. Please advise: how is a pull request created? I did not have access to push up the branch that includes my changes ("people-search"). Thanks.

**Comment by Abdur-rahmaanJ** [comment]
Thanks @mghall25 ! You have twitter by the way? We'd like to give you a shoutout!
