### ISSUE TITLE
Add theming support - bootstrap

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#5]
If you know bootstrap, try implementing theming. See screenshots, currently it's black, it'll be a nice challenge to implement theming in a flask app. Gurl, get those grey matters running

**Comment by jules23** [comment]
Hey! I know bootstrap so I think I can tackle this. Just need some help building your project, I've done a little bit of research unsuccessful so far. Where/how do you recommend I get flask?

**Comment by Abdur-rahmaanJ** [comment]
@jules23 download python 3.7, cd into folder and run ```python -m pip install -r requirements.txt``` then run the instructions in the readme!

**Comment by jules23** [comment]
Awesome it's now working!

**Comment by Abdur-rahmaanJ** [comment]
@jules23 btw read a bit on jinja to see what's going on ^^_

**Comment by blips5** [comment]
@jules23 are you still working on this?

@Abdur-rahmaanJ is there some more info about the bootstrap themes is this just for a single theme or are multiple bootstrap themes wanted?

**Comment by Abdur-rahmaanJ** [comment]
@blips5 multiple themes like we can change 
- icon set
- nav colour
- background image

**Comment by Abdur-rahmaanJ** [comment]
or we can just add them in settings

**Comment by blips5** [comment]
So I've had a look is this what the app is after 

![color_change](https://user-images.githubusercontent.com/33946380/61570265-61d07580-aa83-11e9-8715-b7793dea38fe.gif)

or is it more 

* bootstrap CSS colors such success, primary, dark 
* or something like [bootswatch.com](url) themes

@Abdur-rahmaanJ Thanks for the invite.

**Comment by jules23** [comment]
Guys I am sorry haven't been online but won't be able to work on this much further.

**Comment by Abdur-rahmaanJ** [comment]
@jules23 np feel free to drop in!

**Comment by CommandReverse** [comment]
As I just starting learning about bootstrap I can take a look into this. It may take a bit of time but it is a great opportunity to learn

**Comment by Abdur-rahmaanJ** [comment]
@CommandReverse The Gif above is a great hint!

**Comment by Abdur-rahmaanJ** [comment]
Completed in PR #180 and #190
