### ISSUE TITLE
Add Unit Tests

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#59]

**Comment by arthurarty** [comment]
Will like to work on this.

**Comment by Abdur-rahmaanJ** [comment]
Done!

**Comment by Abdur-rahmaanJ** [comment]
@arthurarty done?

**Comment by arthurarty** [comment]
@Abdur-rahmaanJ Hey yes this is done. We now just need to write tests for each module in the app.

**Comment by Abdur-rahmaanJ** [comment]
opening separate module

**Comment by arthurarty** [comment]
I did not understand that ? Please clarify what you mean by opening a separate module.

**Comment by Abdur-rahmaanJ** [comment]
a separate issue, my bad
