### ISSUE TITLE
Add Payroll Section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#62]
-  Requires Employee model
- This is primarily for learning. We encourage first timers. Please join our discord to have a chat!

**Comment by abimael-o-o** [comment]
Hi, I'm a first timer is it possible for me to take this?

**Comment by blips5** [comment]
Ye  no problem.

**Comment by abimael-o-o** [comment]
Can I get some instructions on what exactly I'm supposed to do and what the result should be? Sorry, I am still quite new to this.

**Comment by blips5** [comment]
Hi abimael-o-o

Have up managed to get everything setup ?

I'll try and break it down a bit. 

first you will need to create a model for employee in the ``model.py`` file  could maybe copy a similar model and adapt it (have a look at [SQLAlchemy](https://docs.sqlalchemy.org/en/13/)
 
Next would be to update the database. (its on the README.md).

Then create your ``views`` in the view directory and then create your ``templates``.

Hope this helps any more questions just ask. 😺

**Comment by abimael-o-o** [comment]
@blips5  sorry how do I setup my local env?

**Comment by blips5** [comment]
Hi abimael-o-o,
Have you got python installed do you know how to make a virtual env.

If so make a fork in top right and make a clone of your shopyo repository. cd into the shopyo folder then follow instructions on the README.md. hope this helps good luck. :smiley_cat:

**Comment by abimael-o-o** [comment]
@blips5 Hi I'm having trouble setting things up 
![image](https://user-images.githubusercontent.com/53713385/74866622-2d76ad80-5321-11ea-94e7-cf3a3b06ddba.png)

**Comment by Abdur-rahmaanJ** [comment]
@abimael-o-o cd into the folder having requirements.txt then run python -m pip install -r requirements.txt

**Comment by abimael-o-o** [comment]
@Abdur-rahmaanJ I did that (Requirement already satisfied) but get same errors

**Comment by Abdur-rahmaanJ** [comment]
@abimael-o-o those are pylint errors. try running python run.py

**Comment by abimael-o-o** [comment]
@Abdur-rahmaanJ  It starts but I cant reach the site 
![image](https://user-images.githubusercontent.com/53713385/74869529-20a88880-5326-11ea-81b4-5d24956b0ab7.png)
![image](https://user-images.githubusercontent.com/53713385/74869561-2f8f3b00-5326-11ea-8e99-5cb53b1f0a88.png)

**Comment by Abdur-rahmaanJ** [comment]
@abimael-o-o go to 127.0.0.1:5000

**Comment by abimael-o-o** [comment]
This?
![image](https://user-images.githubusercontent.com/53713385/74869772-96acef80-5326-11ea-9e2b-15d54b16197e.png)

**Comment by Abdur-rahmaanJ** [comment]
@abimael-o-o now see the readme where you have to run python manage.py db init etc

**Comment by abimael-o-o** [comment]
@Abdur-rahmaanJ  Okay, do I run those commands again?

**Comment by Abdur-rahmaanJ** [comment]
yes!

**Comment by abimael-o-o** [comment]
@Abdur-rahmaanJ  Okay I ran all three and still got this 
![image](https://user-images.githubusercontent.com/53713385/74870525-e17b3700-5327-11ea-80ba-fcec370687a9.png)

**Comment by Abdur-rahmaanJ** [comment]
delete db and migrations folder and try the 5 commands in order

**Comment by abimael-o-o** [comment]
@Abdur-rahmaanJ  I don't see those folders?
![image](https://user-images.githubusercontent.com/53713385/74871346-50a55b00-5329-11ea-9d27-4caa951bf2c4.png)

**Comment by blips5** [comment]
@abimael-o-o  you my need to use file explorer to see them may not show in the IDE.

![db](https://user-images.githubusercontent.com/33946380/74874220-844ba980-5358-11ea-9ae2-815d1ee87c80.PNG)

**Comment by abimael-o-o** [comment]
Seems like I don't have it
![image](https://user-images.githubusercontent.com/53713385/74876372-8d755000-5331-11ea-9a4e-5897e11e079d.png)

**Comment by blips5** [comment]
@abimael-o-o how did you get the project did clone it or download.
 if you downloaded it. Did you extract the zip files before running the project?
😺

**Comment by abimael-o-o** [comment]
I cloned the repo

**Comment by blips5** [comment]
@abimael-o-o  i deleted my local and recreated the bug 

see if you have file test.db and delete it if it not their still try rest of instructions

un comment the db.create() all in the initialize.py file.
run python manage.py db init

run python apply_settings.py

run python run.py

😺

**Comment by abimael-o-o** [comment]
Thank you! @blips5 @Abdur-rahmaanJ  It works now

**Comment by blips5** [comment]
:smiley_cat:
