### ISSUE TITLE
Add Accounting Section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#63]
- Feel free to do some research
- This is primarily for learning. We encourage first timers. Please join our discord to have a chat!

**Comment by IamAbbey** [comment]
I'ld like to take up this issue

**Comment by mpatelia** [comment]
I would like to take this issue if not assigned to anyone.

**Comment by Abdur-rahmaanJ** [comment]
@mpatelia Given the general trend of the project, the first who PR the accounting section frontend is merged!
