### ISSUE TITLE
Add Point of Sales section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#64]
-  Integrates with products
- This is primarily for learning. We encourage first timers. Please join our discord to have a chat!

**Comment by theOpetunde** [comment]
Hello,

I'd like to take up this issue. Thank you

**Comment by theimperium20** [comment]
@Abdur-rahmaanJ Can you provide more details on what you are expecting? Maybe you can leave a link to the discord.

**Comment by Abdur-rahmaanJ** [comment]
@theimperium20  [https://discord.gg/k37Ef6w]()

Basically a checkout page that is a point of sales where you can add products and customer pays.
see this [google seqarch for point of sales screenshote](https://www.google.com/search?q=point+of+sales+screenshot&tbm=isch&ved=2ahUKEwij2rnd-pHoAhUK4hoKHTjDCZwQ2-cCegQIABAA)

You might take odoo point of sales as inspiration!

![odoopos](https://user-images.githubusercontent.com/22630684/76395421-b87f1c80-6390-11ea-8b19-51f0ec52c531.jpg)

**Comment by Abdur-rahmaanJ** [comment]
Basics addedin PR #173
