### ISSUE TITLE
Add Images to Products

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#65]
- Let users upload image
- This is primarily for learning. We encourage first timers. Please join our discord to have a chat!

**Comment by Ruben80** [comment]
Can I help with this issue?

**Comment by Abdur-rahmaanJ** [comment]
@Ruben80 yes!

**Comment by will-commited** [comment]
Hi I was wondering could I work on this please, have to do a project for college of contributing to a project and this looks ideal.

**Comment by blips5** [comment]
@will-commited  Hi this issue has already been assigned. your free to choose another or maybe load up the project, find one and fix it. 😸

**Comment by Abdur-rahmaanJ** [comment]
@Ruben80 How is the issue going?

**Comment by Abdur-rahmaanJ** [comment]
@will-commited how is the issue going?

**Comment by Abdur-rahmaanJ** [comment]
I did it in PR #195
