### ISSUE TITLE
Add appointment section

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#7]
add another view -> appointments/meetings, see products and do the same | any help needed ask!

**Comment by ouyangjunfei** [comment]
I'm a beginner in contributing. Can I handle this? If there are specific requirements, please tell me!

**Comment by Abdur-rahmaanJ** [comment]
@ouyangjunfei no just gear your files so that appointments can be created, active ones and non-active ones can be viewed!

**Comment by ouyangjunfei** [comment]
@Abdur-rahmaanJ
- May I *Reformat* your python codes under `application/` using PyCharm?
- I would like to know what's the `patient` module for
- And I see there're errors in `application/views/people.py products.py`, do i have to handle them?

**Comment by Abdur-rahmaanJ** [comment]
@ouyangjunfei  run initialise.py before you will not have errors

the patient module is in-progress demo of the module system

check manage.py to understand

**Comment by Abdur-rahmaanJ** [comment]
closed by PR #11
