### ISSUE TITLE
Check if files and folders exist before deleting in manage.py

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [Abdur-rahmaanJ/shopyo#93]
In [manage.py](https://github.com/Abdur-rahmaanJ/shopyo/blob/master/shopyo/manage.py)  we have

```python
@manager.command
def clean():
    os.remove('test.db')
    shutil.rmtree('__pycache__')
    shutil.rmtree('migrations')
```

but, if add either try catch or exists function to check if file or folders exist before deleting and informs users of deletion or non-existence

**Comment by Yubhav** [comment]
Can I work on this? This is my first time contributing. @Abdur-rahmaanJ

**Comment by blips5** [comment]
Assigned 😺

**Comment by Yubhav** [comment]
Can you please check it once? I've made the changes. And please help me test it.

**Comment by Yubhav** [comment]
https://github.com/Yubhav/shopyo/commit/f162ca1a8782b88b620687164e64b8ad3db74e84
Please check it once I've made the necessary changes. And help me test it.
